[project]
name = "fbd2026"
version = "0.1.0"
description = "Exemplo prático da disciplina de Fundamento de Banco de Dados"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker==40.39.0",
    "nicegui==3.17.1",
    "psycopg2-binary==2.9.13",
    "pydantic-settings==2.15.0",
    "sqlalchemy==2.1.1",
]
